version: 2
updates:
  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"

    # Only create PRs for specific critical dependencies
    allow:
      - dependency-name: "yt-dlp"
        # yt-dlp is critical - always monitor
      - dependency-name: "openai"
        # API changes can break functionality
      - dependency-name: "anthropic"
        # API changes can break functionality

    # Customize PR settings
    open-pull-requests-limit: 3

    # Add labels for easy filtering
    labels:
      - "dependencies"
      - "python"
      - "automated-pr"

    # Customize commit message
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

    # Group updates when possible
    groups:
      llm-providers:
        patterns:
          - "openai"
          - "anthropic"

      youtube-processing:
        patterns:
          - "yt-dlp"
          - "youtube-transcript-api"
          - "pytube"

    # Ignore certain updates
    ignore:
      # Don't auto-update torch (too large, needs manual testing)
      - dependency-name: "torch"
      - dependency-name: "transformers"
      # Don't auto-update PyQt (GUI changes need testing)
      - dependency-name: "PyQt6"

    # Reviewers (optional - uncomment and add GitHub usernames)
    # reviewers:
    #   - "msg43"

    # Assignees (optional - uncomment and add GitHub usernames)
    # assignees:
    #   - "msg43"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"

    labels:
      - "dependencies"
      - "github-actions"
      - "automated-pr"
