name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have read the troubleshooting section in README.md
          required: true
          
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is
      placeholder: Describe the issue you encountered
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS Sonoma (14.x)
        - macOS Monterey (12.x)
        - macOS Big Sur (11.x)
        - Other (please specify in additional context)
    validations:
      required: true
      
  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.9.1"
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (from GUI console or logs/ directory)
      render: shell
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here 