# Credentials Configuration File
# Copy this file to config/credentials.yaml and fill in your actual API keys
# The credentials.yaml file will be ignored by git for security

api_keys:
  # Bright Data API Key (Recommended for YouTube processing)
  # More cost-effective than monthly proxy subscriptions - pay per request
  # Get your API key at: https://brightdata.com/
  # Benefits: Direct JSON responses, automatic IP rotation, reliable access
  bright_data_api_key: "bd_your_bright_data_api_key_here"
  
  # Bright Data Proxy Credentials (Optional - for enhanced proxy functionality)
  # These are separate from the API key and enable residential proxy sessions
  # Get these from your Bright Data dashboard under "Proxy & Scraping Infrastructure"
  bright_data_customer_id: "c_your_customer_id"  # BD_CUST environment variable
  bright_data_zone_id: "your_zone_name"         # BD_ZONE environment variable  
  bright_data_password: "your_zone_password"    # BD_PASS environment variable

  # WebShare removed; configure only Bright Data credentials

  # OpenAI API Key (Required for GPT-based summarization)
  # Get your key at: https://platform.openai.com/api-keys
  openai: "sk-your_openai_key_here"

  # Anthropic API Key (Required for Claude-based summarization)
  # Get your key at: https://console.anthropic.com/
  anthropic: "sk-ant-your_anthropic_key_here"

  # HuggingFace Token (Required for speaker diarization)
  # Get your free token at: https://huggingface.co/settings/tokens
  hf_token: "hf_your_huggingface_token_here"

  # Optional: YouTube Data API v3 Key (for additional metadata)
  # Get from: https://console.developers.google.com/
  youtube_api_key: "your_youtube_api_key_here"
