# Configuration to disable YouTube processing delays when using rotating proxies
# This should significantly speed up YouTube URL processing

youtube_processing:
  # Disable all delays when using proxies
  disable_delays_with_proxy: true
  
  # Alternatively, set delays to 0 to disable them completely
  metadata_delay_min: 0.0
  metadata_delay_max: 0.0
  transcript_delay_min: 0.0
  transcript_delay_max: 0.0
  api_batch_delay_min: 0.0
  api_batch_delay_max: 0.0
  
  # Don't use delays even when proxies are configured
  use_proxy_delays: false

# Make sure your proxy credentials are configured
api_keys:
  webshare_username: "${WEBSHARE_USERNAME}"
  webshare_password: "${WEBSHARE_PASSWORD}" 