[project]
name = "hce_kit"
version = "0.1.0"
description = "Hybrid Claim Extractor starter kit"
requires-python = ">=3.10"
dependencies = [
  "pydantic>=2.6",
  "numpy>=1.26"
]

[tool.pytest.ini_options]
pythonpath = ["."]
