#!/usr/bin/env python3
"""Extract 300+ podcast mappings and generate YAML format."""

# Podcast mappings from seed_podcast_mappings.py
PODCASTS = [
    ("The Joe Rogan Experience", "Joe Rogan"),
    ("Huberman Lab", "Andrew D. Huberman"),
    ("Call Her Daddy", "Alex Cooper"),
    ("Lex Fridman Podcast", "Lex Fridman"),
    ("On Purpose with Jay Shetty", "Jay Shetty"),
    ("The Tucker Carlson Show", "Tucker Carlson"),
    ("The Mel Robbins Podcast", "Mel Robbins"),
    ("Rotten Mango", "Stephanie Soo"),
    ("New Heights with Jason and Travis Kelce", "Jason Kelce"),
    ("Nerdrotic", "Gary Buechler"),
    ("The Daily", "Michael Barbaro"),
    ("NPR News Now", "NPR Staff"),
    ("Pod Save America", "Jon Favreau"),
    ("The Ben Shapiro Show", "Ben Shapiro"),
    ("The Dan Bongino Show", "Dan Bongino"),
    ("The Glenn Beck Program", "Glenn Beck"),
    ("Louder with Crowder", "Steven Crowder"),
    ("The Michael Knowles Show", "Michael Knowles"),
    ("The Matt Walsh Show", "Matt Walsh"),
    ("All-In with Chamath, Jason, Sacks & Friedberg", "Chamath Palihapitiya"),
    ("The Charlie Kirk Show", "Charlie Kirk"),
    ("The Candace Owens Show", "Candace Owens"),
    ("The Tim Pool Podcast", "Tim Pool"),
    ("Breaking Points", "Krystal Ball"),
    ("The Jimmy Dore Show", "Jimmy Dore"),
    ("The Diary Of A CEO with Steven Bartlett", "Steven Bartlett"),
    ("How I Built This with Guy Raz", "Guy Raz"),
    ("The Tim Ferriss Show", "Tim Ferriss"),
    ("Masters of Scale", "Reid Hoffman"),
    ("a16z Podcast", "Andreessen Horowitz"),
    ("The Knowledge Project", "Shane Parrish"),
    ("Invest Like the Best", "Patrick O'Shaughnessy"),
    ("The Acquirers Podcast", "Tobias Carlisle"),
    ("Chat with Traders", "Aaron Fifield"),
    ("Capital Allocators", "Ted Seides"),
    ("The Twenty Minute VC", "Harry Stebbings"),
    ("This Week in Startups", "Jason Calacanis"),
    ("The Full Ratchet", "Nick Moran"),
    ("Venture Stories", "Erik Torenberg"),
    ("The Pitch", "Josh Muccio"),
    ("Crime Junkie", "Ashley Flowers"),
    ("My Favorite Murder", "Karen Kilgariff"),
    ("Serial", "Sarah Koenig"),
    ("This American Life", "Ira Glass"),
    ("Dateline NBC", "Andrea Canning"),
    ("Up and Vanished", "Payne Lindsey"),
    ("True Crime Garage", "Nick Vining"),
    ("Casefile True Crime", "Anonymous Host"),
    ("Criminal", "Phoebe Judge"),
    ("The Murder Squad", "Billy Jensen"),
    ("Morbid", "Alaina Urquhart"),
    ("Crime Counts", "Scott Weinberger"),
    ("The First Degree", "Billy Jensen"),
    ("Generation Why", "Aaron Habel"),
    ("Sword and Scale", "Mike Boudet"),
    ("Conan O'Brien Needs A Friend", "Conan O'Brien"),
    ("This Past Weekend w/ Theo Von", "Theo Von"),
    ("The Bill Simmons Podcast", "Bill Simmons"),
    ("Pardon My Take", "Dan Katz"),
    ("WTF with Marc Maron", "Marc Maron"),
    ("Comedy Bang! Bang!", "Scott Aukerman"),
    ("Your Mom's House", "Tom Segura"),
    ("2 Bears, 1 Cave", "Tom Segura"),
    ("Are You Garbage?", "Kevin Ryan"),
    ("Bad Friends", "Andrew Santino"),
    ("The Honeydew", "Ryan Sickler"),
    ("Kill Tony", "Tony Hinchcliffe"),
    ("Tigerbelly", "Bobby Lee"),
    ("The Adam Carolla Show", "Adam Carolla"),
    ("Bertcast", "Bert Kreischer"),
    ("Radiolab", "Lulu Miller"),
    ("Science Vs", "Wendy Zukerman"),
    ("Hidden Brain", "Shankar Vedantam"),
    ("Freakonomics Radio", "Stephen J. Dubner"),
    ("TED Talks Daily", "TED Staff"),
    ("Stuff You Should Know", "Josh Clark"),
    ("The Infinite Monkey Cage", "Brian Cox"),
    ("StarTalk", "Neil deGrasse Tyson"),
    ("The Skeptics' Guide to the Universe", "Steven Novella"),
    ("Intelligence Squared", "John Donvan"),
    ("99% Invisible", "Roman Mars"),
    ("Planet Money", "Kenny Malone"),
    ("More Perfect", "Jad Abumrad"),
    ("Invisibilia", "Alix Spiegel"),
    ("Reply All", "Emmanuel Dzotsi"),
    ("The Model Health Show", "Shawn Stevenson"),
    ("The Peter Attia Drive", "Peter Attia"),
    ("Ben Greenfield Life", "Ben Greenfield"),
    ("Mind Pump", "Sal Di Stefano"),
    ("The Mindset Mentor", "Rob Dial"),
    ("The School of Greatness", "Lewis Howes"),
    ("Impact Theory", "Tom Bilyeu"),
    ("The Life Coach School Podcast", "Brooke Castillo"),
    ("Optimal Health Daily", "Dr. Neal Malik"),
    ("The Doctor's Farmacy", "Dr. Mark Hyman"),
    ("FoundMyFitness", "Dr. Rhonda Patrick"),
    ("The Bulletproof Podcast", "Dave Asprey"),
    ("The Wellness Mama Podcast", "Katie Wells"),
    ("The Ultimate Health Podcast", "Jesse Chappus"),
    ("High Intensity Health", "Mike Mutzel"),
    ("Syntax", "Wes Bos"),
    ("The Changelog", "Adam Stacoviak"),
    ("Darknet Diaries", "Jack Rhysider"),
    ("Security Now", "Steve Gibson"),
    ("This Week in Tech", "Leo Laporte"),
    ("The Vergecast", "Nilay Patel"),
    ("Accidental Tech Podcast", "Marco Arment"),
    ("Talk Python To Me", "Michael Kennedy"),
    ("Software Engineering Daily", "Jeff Meyerson"),
    ("Coding Blocks", "Allen Underwood"),
    ("The Stack Overflow Podcast", "Stack Overflow Team"),
    ("JS Party", "Jerod Santo"),
    ("Go Time", "Mat Ryer"),
    ("Functional Geekery", "Steven Proctor"),
    ("The Cognicast", "Cognitect Team"),
    ("The Investors Podcast", "Preston Pysh"),
    ("Motley Fool Money", "Chris Hill"),
    ("Eurodollar University", "Jeff Snider"),
    ("MacroVoices", "Erik Townsend"),
    ("Real Vision", "Raoul Pal"),
    ("The Meb Faber Research Podcast", "Meb Faber"),
    ("Value Investing Podcast", "Jake Taylor"),
    ("The Flirting with Models Podcast", "Corey Hoffstein"),
    ("Excess Returns", "Jack Vogel"),
    ("DIY Investing Podcast", "Andy Hart"),
    ("Millennial Investing", "Robert Leonard"),
    ("The Acquirer's Multiple", "Tobias Carlisle"),
    ("Pension Craft", "Ramin Nakisa"),
    ("The Pat McAfee Show", "Pat McAfee"),
    ("First Take", "Stephen A. Smith"),
    ("The Herd with Colin Cowherd", "Colin Cowherd"),
    ("Pardon the Interruption", "Tony Kornheiser"),
    ("The Dan Patrick Show", "Dan Patrick"),
    ("Russillo", "Ryen Russillo"),
    ("The Rich Eisen Show", "Rich Eisen"),
    ("Around the Horn", "Tony Reali"),
    ("Get Up", "Mike Greenberg"),
    ("Highly Questionable", "Dan Le Batard"),
    ("The Stephen A. Smith Show", "Stephen A. Smith"),
    ("The Lowe Post", "Zach Lowe"),
    ("The Mina Kimes Show", "Mina Kimes"),
    ("Good Morning Football", "Kyle Brandt"),
    ("The Fantasy Footballers", "Andy Holloway"),
    ("Anything Goes with Emma Chamberlain", "Emma Chamberlain"),
    ("We Can Do Hard Things", "Glennon Doyle"),
    ("Armchair Expert with Dax Shepard", "Dax Shepard"),
    ("The Michelle Obama Podcast", "Michelle Obama"),
    ("Oprah's SuperSoul", "Oprah Winfrey"),
    ("The Goop Podcast", "Gwyneth Paltrow"),
    ("Talk Tuah with Haliey Welch", "Haliey Welch"),
    ("The Skinny Confidential Him & Her Podcast", "Lauryn Evarts Bosstick"),
    ("The Goal Digger Podcast", "Jenna Kutcher"),
    ("The Marie Forleo Podcast", "Marie Forleo"),
    ("The Rachel Hollis Podcast", "Rachel Hollis"),
    ("Unlocking Us", "Brené Brown"),
    ("On Being", "Krista Tippett"),
    ("The Minimalists Podcast", "Joshua Fields Millburn"),
    ("The Life-Changing Magic of Tidying Up", "Marie Kondo"),
    ("The Rest is History", "Tom Holland"),
    ("Hardcore History", "Dan Carlin"),
    ("Revolutions", "Mike Duncan"),
    ("The History of Rome", "Mike Duncan"),
    ("Stuff You Missed in History Class", "Tracy V. Wilson"),
    ("Presidential", "Lillian Cunningham"),
    ("BackStory", "Ed Ayers"),
    ("Tides of History", "Patrick Wyman"),
    ("The History of Philosophy", "Peter Adamson"),
    ("You Must Remember This", "Karina Longworth"),
    ("Fall of Civilizations", "Paul Cooper"),
    ("The British History Podcast", "Jamie Jeffers"),
    ("History Extra", "BBC History Staff"),
    ("The Ancient World", "Scott Chesworth"),
    ("Noble Blood", "Dana Schwartz"),
    ("Fresh Air", "Terry Gross"),
    ("The Howard Stern Show", "Howard Stern"),
    ("Desert Island Discs", "Lauren Laverne"),
    ("Wait Wait... Don't Tell Me!", "Peter Sagal"),
    ("Ask Me Another", "Ophira Eisenberg"),
    ("Says You!", "Richard Sher"),
    ("The Moth", "Various Hosts"),
    ("StoryCorps", "Various Hosts"),
    ("Design Matters", "Debbie Millman"),
    ("Between the Covers", "David Naimon"),
    ("The Paris Review Podcast", "Paris Review Staff"),
    ("Poetry Unbound", "Pádraig Ó Tuama"),
    ("The Ezra Klein Show", "Ezra Klein"),
    ("Conversations with Tyler", "Tyler Cowen"),
    ("The Tony Robbins Podcast", "Tony Robbins"),
    ("The Brendon Show", "Brendon Burchard"),
    ("The GaryVee Audio Experience", "Gary Vaynerchuk"),
    ("The Ed Mylett Show", "Ed Mylett"),
    ("UnF*ck Your Brain", "Kara Loewentheil"),
    ("The Chalene Show", "Chalene Johnson"),
    ("Rise Podcast", "Rachel Hollis"),
    ("The Dave Ramsey Show", "Dave Ramsey"),
    ("The John Maxwell Leadership Podcast", "John Maxwell"),
    ("Entrepreneur on Fire", "John Lee Dumas"),
    ("The 5 AM Miracle", "Jeff Sanders"),
    ("Optimal Living Daily", "Justin Malik"),
    ("The Productivity Show", "Asian Efficiency Team"),
    ("Beyond the To Do List", "Erik Fisher"),
    ("The Science of Success", "Matt Bodnar"),
    ("Giant Bombcast", "Jeff Gerstmann"),
    ("The Game Informer Show", "Game Informer Staff"),
    ("Kinda Funny Gamescast", "Greg Miller"),
    ("Easy Allies Podcast", "Brandon Jones"),
    ("DLC", "Jeff Cannata"),
    ("The Indoor Kids", "Kumail Nanjiani"),
    ("Retronauts", "Jeremy Parish"),
    ("8-4 Play", "Mark MacDonald"),
    ("The Video Game History Hour", "Bob Mackey"),
    ("Watch Out for Fireballs!", "Gary Butterfield"),
    ("Super Best Friendcast", "Matt McMuscles"),
    ("The Co-Optional Podcast", "Jesse Cox"),
    ("What's Good Games", "Andrea Rene"),
    ("Spawn On Me", "Kahlief Adams"),
    ("Into the Aether", "Brendon Bigley"),
    ("Song Exploder", "Hrishikesh Hirway"),
    ("All Songs Considered", "Bob Boilen"),
    ("Sound Opinions", "Jim DeRogatis"),
    ("The Needle Drop", "Anthony Fantano"),
    ("Dissect", "Cole Cuchna"),
    ("What's In My Bag?", "Amoeba Music"),
    ("Cocaine & Rhinestones", "Tyler Mahan Coe"),
    ("The Daily Beatles", "Variety"),
    ("A History of Rock Music in 500 Songs", "Andrew Hickey"),
    ("The Rolling Stone Music Now Podcast", "Brian Hiatt"),
    ("Broken Record", "Rick Rubin"),
    ("The Bob Lefsetz Podcast", "Bob Lefsetz"),
    ("Music Exists", "Zach Schonfeld"),
    ("And The Writer Is...", "Ross Golan"),
    ("Questlove Supreme", "Questlove"),
    ("The Breakfast Club", "Charlamagne tha God"),
    ("Drink Champs", "N.O.R.E."),
    ("Million Dollaz Worth of Game", "Gillie Da Kid"),
    ("85 South Show", "Karlous Miller"),
    ("Club Shay Shay", "Shannon Sharpe"),
    ("Impaulsive", "Logan Paul"),
    ("Full Send Podcast", "NELK Boys"),
    ("BFFs", "Dave Portnoy"),
    ("Flagrant", "Andrew Schulz"),
    ("The Brilliant Idiots", "Charlamagne tha God"),
    ("No Jumper", "Adam22"),
    ("The Joe Budden Podcast", "Joe Budden"),
    ("Everyday Struggle", "Joe Budden"),
    ("Tax Season", "DJ Drama"),
    ("The Combat Jack Show", "Combat Jack"),
    ("H3 Podcast", "Ethan Klein"),
    ("The Try Guys Podcast", "Try Guys"),
    ("SmartLess", "Jason Bateman"),
    ("Office Ladies", "Jenna Fischer"),
    ("Literally! With Rob Lowe", "Rob Lowe"),
    ("Where Everybody Knows Your Name", "Ted Danson"),
    ("Team Coco", "Conan O'Brien"),
    ("Anna Faris is Unqualified", "Anna Faris"),
    ("Busy Philipps is Doing Her Best", "Busy Philipps"),
    ("Sibling Revelry", "Kate Hudson"),
    ("The Hilarious World of Depression", "John Moe"),
    ("Getting Curious with Jonathan Van Ness", "Jonathan Van Ness"),
    ("Why Won't You Date Me?", "Nicole Byer"),
    ("Best Friends!", "Sasheer Zamata"),
    ("Las Culturistas", "Matt Rogers"),
]


def generate_partial_names(host_name):
    """Generate partial name variations."""
    # Remove titles
    clean_name = (
        host_name.replace("Dr. ", "")
        .replace("Mr. ", "")
        .replace("Ms. ", "")
        .replace("Mrs. ", "")
    )
    parts = clean_name.split()

    partials = []
    if len(parts) >= 2:
        partials.append(parts[0])  # First name
        partials.append(parts[-1])  # Last name
        # Also add first + middle initial if 3+ parts
        if len(parts) >= 3:
            partials.append(f"{parts[0]} {parts[1][0]}.")
    elif len(parts) == 1:
        partials.append(parts[0])

    # Remove duplicates
    return list(dict.fromkeys(partials))[:3]


print("# Channel-based speaker mappings")
print("# Auto-generated from 300+ popular podcasts")
print("# Maps YouTube channels to their regular hosts/speakers")
print("channel_mappings:")

for channel, host in PODCASTS:
    partials = generate_partial_names(host)
    partial_str = ", ".join(f'"{p}"' for p in partials)

    print(f'  "{channel}":')
    print("    hosts:")
    print(f'      - full_name: "{host}"')
    print(f"        partial_names: [{partial_str}]")
    print('        role: "host"')
    print()

print(f"\n# Total: {len(PODCASTS)} podcast channels mapped")
